title: Willyzw
logo: /assets/img/portrait.jpg
description: Life-long learner aka. PhD student specializing in SLAM for augmented reality.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
